#!/bin/bash

# switch = "!git co $(git recent | fzf)"
# switchall = "!git co $(git branch -r | awk '{ print $1 }' | sed -e 's/origin\\///g' | fzf)"
# recent = "for-each-ref --count=15 --sort=-committerdate refs/heads/ --format='%(refname:short)'"

function get_recent_branches() {
  git for-each-ref --count=15 --sort=-committerdate refs/heads/ --format='%(refname:short)'
}

git checkout $(get_recent_branches | fzf)
